### ISSUE TITLE
并行上传的奥秘？为什么文件分片上传比单文件上传要快？

### ISSUE THREAD

**Issue by erencoding** [SugarTurboS/Sugar-Community#13]
在前段时间，基于公司内部的云存储服务，实现了一个完整的分片上传工具。目前的实现是：每个分片的大小为4m，默认并行上传4个分片为一个轮次，一轮次结束后进行下一轮次。部分性能测试数据如下：

> 网速为4G，文件大小为60M，单文件上传时间为28s，分片上传为19s；
网速为200k/s，文件大小为60M，单文件上传时间为238s，分片上传为33s;

除以上实验条件外，在在同一时间内，如果有其他云存储使用者也会影响上传速度。但是经过多次实验，大文件分片上传的速度都是高于单文件上传。

今天突然想到了这么一个问题：
> 如果网速恒定为1M/s，文件上传的时间为100s，那么100s内，最多只能上传100M的文件，那么串行和并行又有什么关系了？就像是堤坝的出水口，每秒可以出水10顿，那么出水之后是一条河流流出，还是多条河流流出的区别在哪里了？

有点像诡辩哈，大概考虑是浏览器的一些性能上的优化，或者接收方在两种情况下是有区别的，但是背后的原理是什么了？

**Comment by ForeverPx** [comment]
我所知道的是

单TCP很难利用满带宽，源于其拥塞控制不精确，受初始窗口设定、窗口增长策略、带宽探测策略等因素的影响。

更多信息可以参考之前看过的文章，第二部分，TCP的症结：http://blog.chinaunix.net/uid-28387257-id-4335291.html
