### ISSUE TITLE
package-lock.json文件合并冲突怎么办

### ISSUE THREAD

**Issue by PDKSophia** [SugarTurboS/Sugar-Community#3]
每次拉去项目代码，总会出现 `package-lock.json` 文件存在冲突，冲突处多到我不想合并，只能删除，然后重新 `npm install` ，除了这个蠢办法，还有其他的解决方式吗？

**Comment by ForeverPx** [comment]
可以写一个git hook，在拉完代码后，自动删除+重新install生成？

**Comment by PDKSophia** [comment]
> 可以写一个git hook，在拉完代码后，自动删除+重新install生成？

这个本质和我手动鼠标右键删除，然后 npm install 有何区别？😂

**Comment by ForeverPx** [comment]
> > 可以写一个git hook，在拉完代码后，自动删除+重新install生成？
> 
> 这个本质和我手动鼠标右键删除，然后 npm install 有何区别？😂

全自动不香么，你想想一天可以少点多少下，鼠标少移多少距离咯。早搞完早收工呀。

**Comment by SamXChen** [comment]
可以试试让代码完成冲突处理：https://github.com/npm/npm-merge-driver

**Comment by SamXChen** [comment]
其实删除 lock 不是很安全的操作，你可以先 stash 你的 package.json，然后全盘接收 别人的 package-lock，然后把你的 package.json pop 出来，解决冲突后，重新安装一下，更新 package-lock，再提交。

**Comment by ForeverPx** [comment]
> 可以试试让代码完成冲突处理：https://github.com/npm/npm-merge-driver

真香

**Comment by LinDaiDai** [comment]
来膜拜大佬们除了这种蠢办法还可以怎样做，蹲一蹲(｢･ω･)｢嘿
