### ISSUE TITLE
redux-saga 的 yiled put 实现机制？

### ISSUE THREAD

**Issue by PDKSophia** [SugarTurboS/Sugar-Community#7]
我们知道，redux 中 dispatch 一个 action 是同步行为。而为了处理异步请求，我们采用了 redux-saga 去做处理，等请求完成，再通过 `ylied put` 去修改 reducer 的值。

下面是我的遇到的情况 1 : 

场景 1 ：正常发起一个 action，修改 reducer 的值，然后组件中监听此 reducer state 值。看打印顺序
```js
// component.js
UNSAFE_componentWillReceiveProps(nextProps) {
    const { value } = nextProps;
    if (value !== this.props.value) {
       console.log('AAAAAAAA')
    }
 }

onClick = () => {
  this.props.dispatch({
    type: 'CHANGE_VALUE',
    data: 1
   })
  console.log('CCCCCC')
}
```
```js
// reducer.js
function testReducer(state =initState, action) {
  switch (action.type) {
    case 'CHANGE_VALUE':
       console.log('BBBBBB')
  }
}
```
大伙猜猜，打印顺序是什么？

打印顺序是 ： `BBBBBB  >  CCCCCC > AAAAAA`

我的猜测是 : 因为发起的 action 是同步的，所以 reducer 文件中会先打印 `BBBBBB`，此时同步代码执行，打印 `CCCCCC`，而之后会在组件下一轮 re-render 中，再打印 `AAAAAA`

----

场景2 ，发起异步请求，然后通过 yield put 去修改 reducer 中 state 的值，然后组件中监听此 reducer state 值。看打印顺序

```js
// component.js
UNSAFE_componentWillReceiveProps(nextProps) {
    const { value } = nextProps;
    if (value !== this.props.value) {
       console.log('AAAAAAAA')
    }
 }

onClick = () => {
  // 发起请求
  this.props.dispatchSagaAction(() => {
    console.log('CCCCCC')
  });
  console.log('EEEEEE')
}
```

```js
// saga.js
const res = yield call(fetch.callAPI);
if (res.code === 0) {
  // 请求完成，再执行 yield put 修改值
   yield put({
      type: 'CHANGE_VALUE',
      data: res.data
    });
    console.log('DDDDDD')
    cb && cb(res.data);
}
```
```js
// reducer.js
function testReducer(state =initState, action) {
  switch (action.type) {
    case 'CHANGE_VALUE':
       console.log('BBBBBB')
  }
}
```
大伙再猜猜，打印结果是什么 ?

居然是 `EEEEEE > BBBBBB > AAAAAA > DDDDDD > CCCCCC`

![image](https://user-images.githubusercontent.com/29560420/95999127-2bd99700-0e68-11eb-905c-510afd236ddb.png)

按照我的理解，如果把 yield put 看成是 dispatch 一个同步 action，那么会先打印 `BBBBBB`，但是接下来应该是先执行同步代码，也就是输出 `DDDDDD`，但很明显，答案不正确。

理论上将，应该是先打印 `BBBBBB` 然后接着打印 `DDDDDD`，之后在组件下一轮 re-render 中，再去打印 `AAAAAA`，可是并不是这样的。

**大家有什么看法吗？**

**Comment by ForeverPx** [comment]
看起来打印顺序没毛病啊

**Comment by PDKSophia** [comment]
> 看起来打印顺序没毛病啊

我所理解的是，在我 `yield put` 后，进入 reducer.js 中打印 BBBBBB，紧接着应该打印DDDDDD，再AAAAAA，但是打印顺序却不同

**Comment by ForeverPx** [comment]
> > 看起来打印顺序没毛病啊
> 
> 我所理解的是，在我 `yield put` 后，进入 reducer.js 中打印 BBBBBB，紧接着应该打印DDDDDD，再AAAAAA，但是打印顺序却不同

你疑惑的点是  BBBBBB后打印出来的是 AAAAAA 而不是 DDDDDD 对吧？

**Comment by PDKSophia** [comment]
是的 @ForeverPx  对比情况1，我所理解的应该是这样的

**Comment by ForeverPx** [comment]
> 是的 @ForeverPx 对比情况1，我所理解的应该是这样的

我理解的是， put方法实际上是通过reducer改变state，如果这个state被map到了某个组件的props，那接下来componentWillReceiveProps就会被触发。这是一个同步的过程。

**Comment by PDKSophia** [comment]
按你这么说，情况1的打印顺序应该是 BBBBBB > AAAAAA > CCCCCC，但最终打印结果与你的结论有所不同。 @ForeverPx

**Comment by deeWong** [comment]
明确一点：
1、put === dispatch
2、yield 一定会返回一个Promise

redux是同步的，当执行CHANGE_VALUE action，Redux 的 value变化，触发组件监听事件，注入一个微任务01。
yield 产生一个Promise，因为put是同步函数，故会立即注入一个新的微任务02。console.log('DDDDDD')必须等待微任务02执行完再执行。
所以后面的顺序是微任务01 -> 微任务02 -> console.log('DDDDDD')
由于console.log('AAAAAAAA')是在微任务01，故先打印AAAAAAAA再打印DDDDDD。

如果把put方法前面的yield去掉，则会先打印DDDDDD再到AAAAAA。

**Comment by ForeverPx** [comment]
> 明确一点：
> 1、put === dispatch
> 2、yield 一定会返回一个Promise
> 
> redux是同步的，当执行CHANGE_VALUE action，Redux 的 value变化，触发组件监听事件，注入一个微任务01。
> yield 产生一个Promise，因为put是同步函数，故会立即注入一个新的微任务02。console.log('DDDDDD')必须等待微任务02执行完再执行。
> 所以后面的顺序是微任务01 -> 微任务02 -> console.log('DDDDDD')
> 由于console.log('AAAAAAAA')是在微任务01，故先打印AAAAAAAA再打印DDDDDD。
> 
> 如果把put方法前面的yield去掉，则会先打印DDDDDD再到AAAAAA。

看了源码？

**Comment by ForeverPx** [comment]
> 按你这么说，情况1的打印顺序应该是 BBBBBB > AAAAAA > CCCCCC，但最终打印结果与你的结论有所不同。 @ForeverPx

其实是没错的，我说的方式，打印出来就是 EEEEEE > BBBBBB > AAAAAA > DDDDDD > CCCCCC， yield相当于是个async
